{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pymssql\n",
    "\n",
    "# Abre conexão com o banco de dados\n",
    "conexao = pymssql.connect(\n",
    "    server=\"teste-datasprints.cumenodwpcwm.sa-east-1.rds.amazonaws.com\",\n",
    "    port = 1433,\n",
    "    user='admin',\n",
    "    password='kz89oi67',\n",
    "    database='teste_enem_db'\n",
    ")\n",
    "\n",
    "\n",
    "\n",
    "#Cursor pra executar queries no banco SQL\n",
    "cursor = conexao.cursor()\n",
    "cursor.execute(\"\"\"\n",
    "--Cargas DIM Frias\n",
    "\n",
    "--Carga DIM_Tipo_Conclusao_EM\n",
    "\n",
    "BEGIN\n",
    "\n",
    "DBCC CHECKIDENT ('[dbo].[dim_tipo_conclusao_em]',RESEED,-3)\n",
    "GO\n",
    "insert into dim_tipo_conclusao_em(ID_Tipo_Conclusao_EM, Descricao_Tipo_Conclusao_EM)\n",
    "values(-2,'Nao Se Aplica')\n",
    "insert into dim_tipo_conclusao_em(ID_Tipo_Conclusao_EM, Descricao_Tipo_Conclusao_EM)\n",
    "values(-1,'Nao Encontrado')\n",
    "DBCC CHECKIDENT ('[dbo].[dim_tipo_conclusao_em]',RESEED,0)\n",
    "GO \n",
    "insert into dim_tipo_conclusao_em(ID_Tipo_Conclusao_EM, Descricao_Tipo_Conclusao_EM)\n",
    "values(1,'Já concluí o Ensino Médio')\n",
    "insert into dim_tipo_conclusao_em(ID_Tipo_Conclusao_EM, Descricao_Tipo_Conclusao_EM)\n",
    "values(2,'Estou cursando e concluirei o Ensino Médio em 2017')\n",
    "insert into dim_tipo_conclusao_em(ID_Tipo_Conclusao_EM, Descricao_Tipo_Conclusao_EM)\n",
    "values(3,'Estou cursando e concluirei o Ensino Médio após 2017')\n",
    "insert into dim_tipo_conclusao_em(ID_Tipo_Conclusao_EM, Descricao_Tipo_Conclusao_EM)\n",
    "values(4,'Não concluí e não estou cursando o Ensino Médio')\n",
    "\n",
    "\n",
    "END\n",
    "\n",
    "--Carga DIM_Estado\n",
    "\n",
    "BEGIN\n",
    "\n",
    "DBCC CHECKIDENT ('[dbo].[DIM_Estado]',RESEED,-2)\n",
    "GO\n",
    "insert into DIM_estado (id_estado, descricao_estado, sigla_estado)\n",
    "values(-2,'Nao Se Aplica','-2')\n",
    "insert into DIM_estado (id_estado, descricao_estado, sigla_estado)\n",
    "values(-1,'Nao Encontrado','-1')\n",
    "DBCC CHECKIDENT ('[dbo].[DIM_Estado]',RESEED,0)\n",
    "GO \n",
    "insert into DIM_estado (id_estado, descricao_estado, sigla_estado)\n",
    "values(1,'ACRE','AC')\n",
    "insert into DIM_estado (id_estado, descricao_estado, sigla_estado)\n",
    "values(2,'ALAGOAS','AL')\n",
    "insert into DIM_estado (id_estado, descricao_estado, sigla_estado)\n",
    "values(3,'AMAPÁ','AP')\n",
    "insert into DIM_estado (id_estado, descricao_estado, sigla_estado)\n",
    "values(4,'AMAZONAS','AM')\n",
    "insert into DIM_estado (id_estado, descricao_estado, sigla_estado)\n",
    "values(5,'BAHIA','BA')\n",
    "insert into DIM_estado (id_estado, descricao_estado, sigla_estado)\n",
    "values(6,'CEARÁ','CE')\n",
    "insert into DIM_estado (id_estado, descricao_estado, sigla_estado)\n",
    "values(7,'DISTRITO FEDERAL','DF')\n",
    "insert into DIM_estado (id_estado, descricao_estado, sigla_estado)\n",
    "values(8,'ESPÍRITO SANTO','ES')\n",
    "insert into DIM_estado (id_estado, descricao_estado, sigla_estado)\n",
    "values(9,'GOIÁS','GO')\n",
    "insert into DIM_estado (id_estado, descricao_estado, sigla_estado)\n",
    "values(10,'MARANHÃO','MA')\n",
    "insert into DIM_estado (id_estado, descricao_estado, sigla_estado)\n",
    "values(11,'MATO GROSSO','MT')\n",
    "insert into DIM_estado (id_estado, descricao_estado, sigla_estado)\n",
    "values(12,'MATO GROSSO DO SUL','MS')\n",
    "insert into DIM_estado (id_estado, descricao_estado, sigla_estado)\n",
    "values(13,'MINAS GERAIS','MG')\n",
    "insert into DIM_estado (id_estado, descricao_estado, sigla_estado)\n",
    "values(14,'PARÁ','PA')\n",
    "insert into DIM_estado (id_estado, descricao_estado, sigla_estado)\n",
    "values(15,'PARAÍBA','PB')\n",
    "insert into DIM_estado (id_estado, descricao_estado, sigla_estado)\n",
    "values(16,'PARANÁ','PR')\n",
    "insert into DIM_estado (id_estado, descricao_estado, sigla_estado)\n",
    "values(17,'PERNAMBUCO','PE')\n",
    "insert into DIM_estado (id_estado, descricao_estado, sigla_estado)\n",
    "values(18,'PIAUÍ','PI')\n",
    "insert into DIM_estado (id_estado, descricao_estado, sigla_estado)\n",
    "values(19,'RIO DE JANEIRO','RJ')\n",
    "insert into DIM_estado (id_estado, descricao_estado, sigla_estado)\n",
    "values(20,'RIO GRANDE DO NORTE','RN')\n",
    "insert into DIM_estado (id_estado, descricao_estado, sigla_estado)\n",
    "values(21,'RIO GRANDE DO SUL','RS')\n",
    "insert into DIM_estado (id_estado, descricao_estado, sigla_estado)\n",
    "values(22,'RONDÔNIA','RO')\n",
    "insert into DIM_estado (id_estado, descricao_estado, sigla_estado)\n",
    "values(23,'RORAIMA','RR')\n",
    "insert into DIM_estado (id_estado, descricao_estado, sigla_estado)\n",
    "values(24,'SANTA CATARINA','SC')\n",
    "insert into DIM_estado (id_estado, descricao_estado, sigla_estado)\n",
    "values(25,'SÃO PAULO','SP')\n",
    "insert into DIM_estado (id_estado, descricao_estado, sigla_estado)\n",
    "values(26,'SERGIPE','SE')\n",
    "insert into DIM_estado (id_estado, descricao_estado, sigla_estado)\n",
    "values(27,'TOCANTINS','TO')\n",
    "\n",
    "END\n",
    "\"\"\")\n",
    "\n",
    "# Comita os dados\n",
    "conexao.commit()\n",
    "# Fecha o cursor\n",
    "cursor.close()\n",
    "\n",
    "# Fecha a conexão\n",
    "conexao.close() "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
