{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pymssql\n",
    "\n",
    "# Abre conexão com o banco de dados\n",
    "conexao = pymssql.connect(\n",
    "    server=\"teste-datasprints.cumenodwpcwm.sa-east-1.rds.amazonaws.com\",\n",
    "    port = 1433,\n",
    "    user='admin',\n",
    "    password='kz89oi67',\n",
    "    database='teste_enem_db'\n",
    ")\n",
    "\n",
    "\n",
    "\n",
    "#Cursor pra executar queries no banco SQL\n",
    "cursor = conexao.cursor()\n",
    "cursor.execute(\"\"\"\n",
    "--Cargas STG\n",
    "\n",
    "--Carga STG_Aluno\n",
    "\n",
    "BEGIN\n",
    "\n",
    "insert into STG_Aluno(TP_ST_CONCLUSAO, NU_INSCRICAO, NU_IDADE, TP_SEXO)\n",
    "select\tTP_ST_CONCLUSAO,\n",
    "\t\tNU_INSCRICAO, \n",
    "\t\tNU_IDADE, \n",
    "\t\tTP_SEXO\n",
    "\t\tfrom MICRODADOS_ENEM\n",
    "\n",
    "END\n",
    "\n",
    "\n",
    "--Carga STG_Cidade\n",
    "\n",
    "BEGIN\n",
    "truncate table STG_Cidade\n",
    "insert into STG_Cidade (id_cidade, cidade, estado, latitude, longitude)\n",
    "select\t\tID,\n",
    "\t\tNM_LOCALID,\n",
    "\t\tNM_UF,\n",
    "\t\tLATITUDE,\n",
    "\t\tLONGITUDE\n",
    "\tFROM Dados_Geograficos_IBGE\n",
    "\tWHERE NM_CATEGOR = 'CIDADE'\n",
    "\n",
    "END\n",
    "\n",
    "\n",
    "--Carga STG_Fato_Notas\n",
    "\n",
    "BEGIN\n",
    "truncate table Stg_Fato_Notas \n",
    "insert into Stg_Fato_Notas (NO_MUNICIPIO_RESIDENCIA, SG_UF_RESIDENCIA, NU_INSCRICAO, NU_NOTA_CN, NU_NOTA_CH, NU_NOTA_LC, NU_NOTA_MT, NU_NOTA_COMP1, NU_NOTA_COMP2, NU_NOTA_COMP3, NU_NOTA_COMP4, NU_NOTA_COMP5, NU_NOTA_REDACAO)\n",
    "select\n",
    "\t\tNO_MUNICIPIO_RESIDENCIA,\n",
    "\t\tSG_UF_RESIDENCIA, \n",
    "\t\tNU_INSCRICAO, \n",
    "\t\tNU_NOTA_CN, \n",
    "\t\tNU_NOTA_CH, \n",
    "\t\tNU_NOTA_LC, \n",
    "\t\tNU_NOTA_MT, \n",
    "\t\tNU_NOTA_COMP1, \n",
    "\t\tNU_NOTA_COMP2, \n",
    "\t\tNU_NOTA_COMP3, \n",
    "\t\tNU_NOTA_COMP4, \n",
    "\t\tNU_NOTA_COMP5, \n",
    "\t\tNU_NOTA_REDACAO\n",
    "from MICRODADOS_ENEM\n",
    "WHERE NU_NOTA_CN > 0\n",
    "AND NU_NOTA_CH > 0\n",
    "AND NU_NOTA_LC > 0\n",
    "AND NU_NOTA_MT > 0\n",
    "AND NU_NOTA_REDACAO > 0\n",
    "\n",
    "END\n",
    "\n",
    "\n",
    "\"\"\")\n",
    "\n",
    "# Comita os dados\n",
    "conexao.commit()\n",
    "# Fecha o cursor\n",
    "cursor.close()\n",
    "\n",
    "# Fecha a conexão\n",
    "conexao.close() "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
